#!/usr/bin/python
import random
import time
f = open('/home/ocoutts/workspace/automated_sync/cron/lograndom.txt', 'a')
number = random.randint(1,1000)
time = time.asctime(time.localtime(time.time()))
f.write('%s Random Number is: %s\n'%(time,number))
f.close()
